// Modul administrasi akses: user disetujui, approval, audit, dan scope organisasi.
import React, { useEffect, useState } from 'react';
import { request } from '../api';

export function PasswordPanel({ onClose }) { const [form, setForm] = useState({ current_password: '', new_password: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); async function save(e) { e.preventDefault(); try { await request('/auth/me/password', { method: 'PUT', body: JSON.stringify(form) }); setMessage('Password berhasil diperbarui.'); setForm({ current_password: '', new_password: '' }); } catch (err) { setError(err.message); } } return <div className="drawer-backdrop"><section className="drawer"><div className="drawer-head"><div><span className="eyebrow">KEAMANAN</span><h2>Ganti password</h2></div><button className="icon-btn" onClick={onClose}>×</button></div><form onSubmit={save} className="form-grid"><label className="full">Password saat ini<input required type="password" value={form.current_password} onChange={e => setForm({ ...form, current_password: e.target.value })} /></label><label className="full">Password baru<input required minLength="8" type="password" value={form.new_password} onChange={e => setForm({ ...form, new_password: e.target.value })} /></label>{error && <div className="alert full">{error}</div>}{message && <div className="hint full">{message}</div>}<div className="actions full"><button type="button" onClick={onClose}>Tutup</button><button className="primary">Simpan password</button></div></form></section></div>; }

// Komponen pagination bersama untuk daftar personel dan administrasi.

export function PagePagination({ meta, onChange }) { const pages = Math.max(1, Math.ceil((meta.total || 0) / (meta.limit || 10))); return <div className="pagination"><button disabled={meta.page <= 1} onClick={() => onChange(meta.page - 1, meta.limit)}>Sebelumnya</button><span>Halaman {meta.page} dari {pages} · {meta.total || 0} data</span><label className="page-size">Tampilkan<select value={meta.limit || 10} onChange={e => onChange(1, Number(e.target.value))}><option value="10">10</option><option value="25">25</option><option value="50">50</option></select></label><button disabled={meta.page >= pages} onClick={() => onChange(meta.page + 1, meta.limit)}>Berikutnya</button></div>; }

// Menampilkan user yang sudah disetujui dan menyediakan perubahan role.

function ApprovedUsersPage() { const [users, setUsers] = useState([]); const [meta, setMeta] = useState({ page: 1, limit: 10, total: 0 }); const [selected, setSelected] = useState(null); const [role, setRole] = useState('viewer'); const [message, setMessage] = useState(''); const [error, setError] = useState(''); async function load(page = meta.page, limit = meta.limit) { try { const result = await request(`/auth/users/approved?page=${page}&limit=${limit}`); setUsers(result.data || []); setMeta(result.meta || { page, limit, total: 0 }); } catch (err) { setError(err.message); } } useEffect(() => { load(1, 10); }, []); async function saveRole(e) { e.preventDefault(); try { await request(`/auth/users/${selected.id_user}/role`, { method: 'PATCH', body: JSON.stringify({ role }) }); setSelected(null); setMessage('Role user berhasil diperbarui.'); load(meta.page, meta.limit); } catch (err) { setError(err.message); } } return <section className="page-section"><div className="page-heading"><div><span className="eyebrow">ADMINISTRASI</span><h1>User Disetujui</h1><p className="muted">Daftar user aktif yang telah melewati proses persetujuan.</p></div></div>{message && <div className="hint">{message}</div>}{error && <div className="alert">{error}</div>}<div className="panel"><div className="table-wrap"><table><thead><tr><th>Username</th><th>Role</th><th>Status</th><th>Dibuat</th><th>Aksi</th></tr></thead><tbody>{users.map(item => <tr key={item.id_user}><td><strong>{item.username}</strong></td><td><span className="badge">{item.role}</span></td><td>Aktif</td><td>{new Date(item.created_at).toLocaleDateString('id-ID')}</td><td><button className="table-action" onClick={() => { setSelected(item); setRole(item.role); }}>Promote role</button></td></tr>)}{!users.length && <tr><td colSpan="5" className="empty">Belum ada user disetujui.</td></tr>}</tbody></table></div><PagePagination meta={meta} onChange={load} /></div>{selected && <div className="drawer-backdrop"><section className="drawer compact-modal"><div className="drawer-head"><div><span className="eyebrow">AKSES USER</span><h2>Promote role</h2></div><button className="icon-btn" onClick={() => setSelected(null)}>×</button></div><p className="muted">Ubah role untuk <strong>{selected.username}</strong>.</p><form onSubmit={saveRole} className="form-grid"><label className="full">Role baru<select value={role} onChange={e => setRole(e.target.value)}><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="operator_satker">Operator Satker</option><option value="operator_polda">Operator Polda</option><option value="admin_ssdm">Admin SSDM</option><option value="admin">Admin</option></select></label><div className="actions full"><button type="button" onClick={() => setSelected(null)}>Batal</button><button className="primary">Simpan role</button></div></form></section></div>}</section>; }

// Mengambil pendaftaran pending dan mengirim keputusan approval admin.

function ApprovalPage() { const [items, setItems] = useState([]); const [meta, setMeta] = useState({ page: 1, limit: 10, total: 0 }); const [roles, setRoles] = useState({}); const [error, setError] = useState(''); async function load(page = meta.page) { try { const result = await request(`/auth/registrations/pending?page=${page}&limit=10`); setItems(result.data || []); setMeta(result.meta || { page, limit: 10, total: 0 }); } catch (err) { setError(err.message); } } useEffect(() => { load(1); }, []); async function decide(item, decision) { try { await request(`/auth/registrations/${item.id_registration}`, { method: 'PATCH', body: JSON.stringify({ decision, approved_role: roles[item.id_registration] || 'viewer' }) }); load(meta.page); } catch (err) { setError(err.message); } } return <section className="page-section"><div className="page-heading"><div><span className="eyebrow">ADMINISTRASI</span><h1>Permintaan Akses</h1><p className="muted">Tinjau identitas pendaftar dan tetapkan role akses.</p></div></div>{error && <div className="alert">{error}</div>}<div className="panel"><div className="table-wrap"><table><thead><tr><th>Identitas</th><th>Username</th><th>Role awal</th><th>Tetapkan role</th><th>Aksi</th></tr></thead><tbody>{items.map(item => <tr key={item.id_registration}><td><strong>{item.nama || '-'}</strong><small>{item.pangkat || '-'} · {item.nip || '-'}</small><small>{item.satker_asal || '-'}</small></td><td>{item.username}</td><td><span className="badge">{item.requested_role}</span></td><td><select value={roles[item.id_registration] || 'viewer'} onChange={e => setRoles({ ...roles, [item.id_registration]: e.target.value })}><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="operator_satker">Operator Satker</option><option value="operator_polda">Operator Polda</option><option value="admin_ssdm">Admin SSDM</option><option value="admin">Admin</option></select></td><td className="actions-cell"><button onClick={() => decide(item, 'reject')}>Tolak</button><button className="primary" onClick={() => decide(item, 'approve')}>Setujui</button></td></tr>)}{!items.length && <tr><td colSpan="5" className="empty">Tidak ada pendaftaran yang menunggu approval.</td></tr>}</tbody></table></div><PagePagination meta={meta} onChange={load} /></div></section>; }

// Menampilkan audit keputusan approval yang sudah diproses.

function ApprovalHistoryPage() { const [items, setItems] = useState([]); const [meta, setMeta] = useState({ page: 1, limit: 10, total: 0 }); const [error, setError] = useState(''); async function load(page = meta.page) { try { const result = await request(`/auth/registrations/history?page=${page}&limit=10`); setItems(result.data || []); setMeta(result.meta || { page, limit: 10, total: 0 }); } catch (err) { setError(err.message); } } useEffect(() => { load(1); }, []); return <section className="page-section"><div className="page-heading"><div><span className="eyebrow">AUDIT AKSES</span><h1>Riwayat Persetujuan</h1><p className="muted">Rekam jejak identitas, keputusan approval, dan aktor yang memprosesnya.</p></div></div>{error && <div className="alert">{error}</div>}<div className="panel"><div className="table-wrap"><table><thead><tr><th>Identitas</th><th>Username</th><th>Status</th><th>Role akhir</th><th>Aktor</th><th>Waktu</th><th>Catatan</th></tr></thead><tbody>{items.map(item => <tr key={item.id_registration}><td><strong>{item.nama || '-'}</strong><small>{item.pangkat || '-'} · {item.nip || '-'}</small><small>{item.satker_asal || '-'}</small></td><td>{item.username}</td><td><span className="badge">{item.status === 'approved' ? 'Disetujui' : 'Ditolak'}</span></td><td>{item.approved_role || '-'}</td><td>{item.reviewer_username || '-'}</td><td>{item.reviewed_at ? new Date(item.reviewed_at).toLocaleString('id-ID') : '-'}</td><td>{item.review_note || '-'}</td></tr>)}{!items.length && <tr><td colSpan="7" className="empty">Belum ada riwayat persetujuan.</td></tr>}</tbody></table></div><PagePagination meta={meta} onChange={load} /></div></section>; }

// Form tambah/edit riwayat jabatan beserta Satker, fungsi, dan level.

function AccessManagementPage({ page, onPage }) { return <section className="page-section"><div className="subpage-nav"><button className={page === 'users' ? 'active' : ''} onClick={() => onPage('users')}>Data User</button><button className={page === 'history' ? 'active' : ''} onClick={() => onPage('history')}>Riwayat Persetujuan</button><button className={page === 'approval' ? 'active' : ''} onClick={() => onPage('approval')}>Permintaan Akses</button><button className={page === 'scopes' ? 'active' : ''} onClick={() => onPage('scopes')}>Scope Organisasi</button></div>{page === 'users' && <ApprovedUsersPage />}{page === 'history' && <ApprovalHistoryPage />}{page === 'approval' && <ApprovalPage />}{page === 'scopes' && <ScopeOrganizationPage />}</section>; }

// Picker Satker bertingkat; level berikutnya muncul sesuai struktur parent.

function ScopeOrganizationPage() {
  const [users, setUsers] = useState([]); const [satkers, setSatkers] = useState([]); const [selected, setSelected] = useState(null); const [scope, setScope] = useState([]); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all(['/auth/users/approved?page=1&limit=100', '/master/satker/tree'].map(path => request(path))).then(([usersResult, satkerResult]) => { setUsers(usersResult.data || []); setSatkers(satkerResult.data || []); }).catch(err => setError(err.message)); }, []);
  async function choose(item) { setSelected(item); setMessage(''); setError(''); try { const result = await request(`/auth/users/${item.id_user}/scopes`); setScope((result.data || []).map(row => Number(row.id_satker))); } catch (err) { setError(err.message); } }
  function toggle(id) { setScope(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); }
  async function save() { if (!selected) return; setSaving(true); setError(''); setMessage(''); try { await request(`/auth/users/${selected.id_user}/scopes`, { method: 'PUT', body: JSON.stringify({ id_satker: scope }) }); setMessage(`Scope ${selected.username} berhasil diperbarui.`); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  return <section className="page-section"><div className="page-heading"><div><span className="eyebrow">ADMINISTRASI</span><h1>Scope Organisasi</h1><p className="muted">Tetapkan Satker yang boleh diakses setiap user operator.</p></div></div>{message && <div className="hint">{message}</div>}{error && <div className="alert">{error}</div>}<div className="scope-layout"><div className="panel"><h2>Daftar user</h2><div className="scope-user-list">{users.map(item => <button key={item.id_user} className={selected?.id_user === item.id_user ? 'selected' : ''} onClick={() => choose(item)}><strong>{item.username}</strong><small>{item.role}</small></button>)}{!users.length && <p className="muted">Belum ada user aktif.</p>}</div></div><div className="panel"><h2>{selected ? `Satker untuk ${selected.username}` : 'Pilih user'}</h2>{selected && <><p className="muted">Centang satu atau beberapa Satker sesuai kewenangan user.</p><div className="scope-checklist">{satkers.map(item => <label key={item.id_satker}><input type="checkbox" checked={scope.includes(Number(item.id_satker))} onChange={() => toggle(Number(item.id_satker))} /><span>{item.nama_satker}<small>{item.kode_satker} · {item.tipe_satker}</small></span></label>)}</div><div className="actions"><button className="primary" disabled={saving} onClick={save}>{saving ? 'Menyimpan…' : 'Simpan scope'}</button></div></>}</div></div></section>;
}

// Menentukan halaman awal administrasi berdasarkan role user.

export function ScopeManagementPage() { const role = (() => { try { return JSON.parse(atob(localStorage.getItem('sdm_token')?.split('.')[1] || '')).role; } catch { return ''; } })(); const [page, setPage] = useState(role === 'admin' ? 'approval' : 'scopes'); return <AccessManagementPage page={page} onPage={setPage} />; }

// Shell aplikasi aktif: navigasi, routing halaman, session, dan layout responsif.
