import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000/api/v1';

async function request(path, options = {}) {
  const token = localStorage.getItem('sdm_token');
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } });
  const body = response.status === 204 ? null : await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || 'Request gagal.');
  return body;
}

function Login({ onLogin }) {
  const [form, setForm] = useState({ username: '', password: '' }); const [error, setError] = useState('');
  async function submit(event) { event.preventDefault(); setError(''); try { const result = await request('/auth/login', { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('sdm_token', result.token); onLogin(result.user); } catch (err) { setError(err.message); } }
  return <main className="login"><section className="login-card"><span className="eyebrow">AS SDM KAPOLRI</span><h1>Merit System Personel</h1><p className="muted">Kelola data personel dan perjalanan karier secara terintegrasi.</p><form onSubmit={submit}><label>Username<input required value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /></label><label>Password<input required type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <div className="alert">{error}</div>}<button className="primary">Masuk ke aplikasi</button></form></section></main>;
}

function App() {
  const [user, setUser] = useState(null); const [people, setPeople] = useState([]); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [error, setError] = useState('');
  async function load() { try { const result = await request(`/pegawai?limit=50&search=${encodeURIComponent(search)}`); setPeople(result.data || []); setError(''); } catch (err) { if (err.message.includes('token') || err.message.includes('Unauthorized')) logout(); else setError(err.message); } }
  useEffect(() => { if (user) load(); }, [user, search]);
  function logout() { localStorage.removeItem('sdm_token'); setUser(null); }
  if (!user) return <Login onLogin={setUser} />;
  return <div className="shell"><aside><div className="brand"><span className="brand-mark">M</span><div><strong>MERIT SYSTEM</strong><small>PERSONEL POLRI</small></div></div><nav><a className="active">◈ Dashboard</a><a>♙ Data Personel</a><a>▤ Riwayat Jabatan</a><a>⚙ Pengaturan</a></nav><div className="user-box"><strong>{user.username}</strong><small>{user.role}</small><button onClick={logout}>Keluar</button></div></aside><main className="content"><header><div><span className="eyebrow">DASHBOARD</span><h1>Data Personel</h1><p className="muted">Pantau kualifikasi dan riwayat jabatan personel dalam satu tempat.</p></div><button className="primary" onClick={() => setSelected({})}>+ Tambah personel</button></header><section className="stats"><div><span>Total personel</span><strong>{people.length}</strong><small>Data dalam scope Anda</small></div><div><span>Jabatan aktif</span><strong>{people.filter(p => p.status_pegawai === 'AKTIF').length}</strong><small>Terdata aktif</small></div><div><span>Akses Anda</span><strong className="capitalize">{user.role}</strong><small>Scope organisasi diterapkan API</small></div></section><section className="panel"><div className="panel-head"><div><h2>Daftar personel</h2><p className="muted">Cari berdasarkan nama atau NRP/NIP.</p></div><input className="search" placeholder="⌕  Cari personel..." value={search} onChange={e => setSearch(e.target.value)} /></div>{error && <div className="alert">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Personel</th><th>NRP / NIP</th><th>Pangkat</th><th>Jabatan</th><th>Status</th><th></th></tr></thead><tbody>{people.map(person => <tr key={person.id_pegawai} onClick={() => setSelected(person)}><td><strong>{person.nama}</strong><small>{person.jenis_kelamin === 'L' ? 'Laki-laki' : 'Perempuan'} · {person.tempat_lahir || '-'}</small></td><td>{person.nip}</td><td>{person.nama_pangkat || '-'}</td><td>{person.nama_jabatan || '-'}</td><td><span className="badge">{person.status_pegawai}</span></td><td className="arrow">›</td></tr>)}{!people.length && <tr><td colSpan="6" className="empty">Belum ada data personel pada scope ini.</td></tr>}</tbody></table></div></section>{selected && <PersonPanel person={selected} onClose={() => setSelected(null)} onSaved={() => { setSelected(null); load(); }} />}</main></div>;
}

function PersonPanel({ person, onClose, onSaved }) { const [form, setForm] = useState({ nip: person.nip || '', nik: person.nik || '', nama: person.nama || '', jenis_kelamin: person.jenis_kelamin || 'L', tempat_lahir: person.tempat_lahir || '', tanggal_lahir: person.tanggal_lahir || '', tanggal_masuk: person.tanggal_masuk || '', id_unit: person.id_unit || '', id_jabatan: person.id_jabatan || '', id_golongan: person.id_golongan || '', status_pegawai: person.status_pegawai || 'AKTIF', batas_usia_pensiun: person.batas_usia_pensiun || 58 }); const [error, setError] = useState('');
  async function save(e) { e.preventDefault(); try { await request(person.id_pegawai ? `/pegawai/${person.id_pegawai}` : '/pegawai', { method: person.id_pegawai ? 'PUT' : 'POST', body: JSON.stringify({ ...form, id_unit: Number(form.id_unit), id_jabatan: Number(form.id_jabatan), id_golongan: Number(form.id_golongan), batas_usia_pensiun: Number(form.batas_usia_pensiun) }) }); onSaved(); } catch (err) { setError(err.message); } }
  return <div className="drawer-backdrop"><section className="drawer"><div className="drawer-head"><div><span className="eyebrow">{person.id_pegawai ? 'EDIT DATA' : 'DATA BARU'}</span><h2>{person.id_pegawai ? person.nama : 'Tambah personel'}</h2></div><button className="icon-btn" onClick={onClose}>×</button></div>{!person.id_pegawai && <p className="hint">Field bertanda * wajib diisi. Riwayat jabatan dapat ditambahkan setelah personel tersimpan.</p>}<form onSubmit={save} className="form-grid">{[['nama','Nama lengkap *'],['nip','NRP / NIP *'],['nik','NIK *'],['tempat_lahir','Tempat lahir']].map(([key, label]) => <label key={key}>{label}<input required={label.endsWith('*')} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<label>Jenis kelamin<select value={form.jenis_kelamin} onChange={e => setForm({ ...form, jenis_kelamin: e.target.value })}><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></label><label>Tanggal lahir *<input required type="date" value={form.tanggal_lahir} onChange={e => setForm({ ...form, tanggal_lahir: e.target.value })} /></label><label>Tanggal masuk *<input required type="date" value={form.tanggal_masuk} onChange={e => setForm({ ...form, tanggal_masuk: e.target.value })} /></label><label>Status<select value={form.status_pegawai} onChange={e => setForm({ ...form, status_pegawai: e.target.value })}><option>AKTIF</option><option>PENSIUN</option><option>NONAKTIF</option></select></label>{error && <div className="alert full">{error}</div>}<div className="actions full"><button type="button" onClick={onClose}>Batal</button><button className="primary">Simpan data</button></div></form></section></div>;
}

createRoot(document.getElementById('root')).render(<App />);
